import running from "../Resources/running.jpeg";

let GroupData = [
  {
    groupid: 1,
    image: running,
    title: "IPPT Training ",
    location: "Our Tampines Hub",
    tags: ["running", "swimming", "cycling", "fun", "group"],
    attendees: 15,
    creator: "Jon. Faveru",
    groupdesc:
      "We focus on training for yearly IPPT test and Lorem ipsum  (need to have certain character limit",

    events: [
      {
        eventid: 1,
        eventimage: running,
        eventtitle: "2.4km training",
        eventlocation: "Our Tampines Hub",
        eventdate: "24/10/2023",
        eventtags: ["Beginner", "Running"],
        eventattendees: 20,
        eventcreator: "Jon. Faveru",
        eventdescription: "We will do 6x400m around the track",
      },
      {
        eventid: 2,
        eventimage: running,
        eventtitle: "2.4km training",
        eventlocation: "Our Tampines Hub",
        eventdate: "24/10/2023",
        eventtags: ["Beginner", "Running"],
        eventattendees: 20,
        eventcreator: "Jon. Faveru",
        eventdescription: "We will do 6x400m around the track",
      },
      {
        eventid: 3,
        eventimage: running,
        eventtitle: "2.4km training",
        eventdate: "24/10/2023",
        eventlocation: "Our Tampines Hub",
        eventtags: ["Beginner", "Running"],
        eventattendees: 20,
        eventcreator: "Jon. Faveru",
        eventdescription: "We will do 6x400m around the track",
      },
      {
        eventid: 4,
        eventimage: running,
        eventtitle: "2.4km training",
        eventdate: "24/10/2023",
        eventlocation: "Our Tampines Hub",
        eventtags: ["Beginner", "Running"],
        eventattendees: 20,
        eventcreator: "Jon. Faveru",
        eventdescription: "We will do 6x400m around the track",
      },
      {
        eventid: 5,
        eventimage: running,
        eventtitle: "2.4km training",
        eventdate: "24/10/2023",
        eventlocation: "Our Tampines Hub",
        eventtags: ["Beginner", "Running"],
        eventattendees: 20,
        eventcreator: "Jon. Faveru",
        eventdescription: "We will do 6x400m around the track",
      },
      {
        eventid: 6,
        eventimage: running,
        eventtitle: "2.5km training",
        eventdate: "24/10/2023",
        eventlocation: "Our Tampines Hub",
        eventtags: ["Beginner", "Running"],
        eventattendees: 20,
        eventcreator: "Jon. Faveru",
        eventdescription: "We will do 6x400m around the track",
      },
    ],
  },
];

export default GroupData;